name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Copy Code folder
        run: |
          rsync -avz --exclude '.*' ./Code/ ./
        env:
          PATH: ${{ runner.tools }}/rsync

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: your_huggingface_username
          SPACE_NAME: your_space_name
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
