name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          lfs: true

      - name: Copy Code folder
        run: |
          # Créez un répertoire temporaire
          mkdir temp_directory

          # Copiez le contenu du dossier "Code" dans le répertoire temporaire
          cp -r ./Code/* temp_directory/

          # Déplacez le contenu du répertoire temporaire à la racine du référentiel
          mv temp_directory/* ./

          # Supprimez le répertoire temporaire
          rmdir temp_directory
        shell: bash

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: your_huggingface_username
          SPACE_NAME: your_space_name
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
