name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd code  # Accéder au répertoire Code
          git init
          git config --global user.name "$FFatih"
          git config --global user.email "f.fatih@outlook.fr"
          git config --global init.defaultBranch main
          git branch -m main
          git add .
          git commit -m "Sync to Hugging Face"
          git push --force "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/gradiotest" main
