name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: F-Fatih/gradiotest  # Remplacez par le chemin de votre référentiel
          path: ./code  # Spécifiez ici le répertoire que vous voulez synchroniser
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
      - name: Push to hub
        run: git push --force https://FFatih:$HF_TOKEN@huggingface.co/spaces/FFatih/gradiotest main
